using System.ComponentModel;

namespace IdleRpgAction.Domain.Enumerations
{
    public enum ActionCommandEnum
    {
        [Description("$status")]
        Status,
        [Description("$adventure")]
        Adventure,
        [Description("$adventures")]
        Adventures,
        [Description("$timings")]
        Cooldowns,
        [Description("$pray")]
        Pray,
        [Description("$favor")]
        Favor,
        [Description("$money")]
        Money,
        [Description("$daily")]
        Daily,
        [Description("$vote")]
        Vote,
        [Description("$battle")]
        Battle,
        [Description("$raidbattle")]
        RaidBattle,
        [Description("$tournament")]
        Tournament,
        [Description("$hungergames")]
        Hungergames,
        [Description("$profile")]
        Profile,
        [Description("$profile2")]
        Profile2,
        [Description("$blackjack")]
        BlackJack,
        [Description("$roulette")]
        Roulette,
        [Description("$flip")]
        Flip,
        [Description("$merge")]
        Merge,
        [Description("$upgrade")]
        Upgrade,
        [Description("$steal")]
        Steal,
        [Description("$inventory")]
        Inventory,
        [Description("$crates")]
        Crates,
        [Description("$open")]
        Open,
        [Description("$sell")]
        Sell,
        [Description("$merchant")]
        Merchant,
        [Description("$shop")]
        Shop,
        [Description("$trade")]
        Trade,
        [Description("$card")]
        Card,
        [Description("$myclass")]
        MyClass,
        [Description("$bet")]
        Bet,
        [Description("$dos")]
        Dos,
        [Description("$roulette table")]
        Roulette_Table,
        [Description("$cancel")]
        Cancel,
        [Description("$activeadventure")]
        ActiveAdventure,
        [Description("$purchase")]
        Purchase,
        [Description("$activate")]
        Activate,
        [Description("$boosters")]
        Boosters
    }
}
